version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: phucdl-test-server-img
    container_name: phucdl-test-server
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./server:/var/www
    networks:
      - phucdl_test

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: phucdl-test-client-img
    container_name: phucdl-test-client
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - phucdl_test

  mongodb:
    image: mongo:latest
    container_name: phucdl-test-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: test
    ports:
      - 29017:27017
    volumes:
      - phucdl_test_mongodb:/data/db
      - ./.docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - phucdl_test

  nginx:
    image: nginx:alpine
    container_name: phucdl-test-nginx
    restart: unless-stopped
    ports:
      - 8100:80
      - 8200:81
    volumes:
      - ./server:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd:ro
    networks:
      - phucdl_test

volumes:
  phucdl_test_mongodb:
networks:
  phucdl_test:
    driver: bridge
